# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_publication', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(max_length=100)),
                ('hour', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('detail', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('show_detail', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-start_date',),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_schedule_eventpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('number', models.IntegerField(default=0)),
                ('template', models.CharField(choices=[(b'djangocms_schedule/widget.html', b'Widget')], max_length=255, verbose_name=b'Template')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
